language: c

git:
  depth: 5

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: AUTOBUILD_SUFFIX=ubuntu
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: EZ_CONFIG_FILE=.config_windows AUTOBUILD_SUFFIX=win32
    - os: osx
      osx_image: xcode6.4
      compiler: gcc
      env: AUTOBUILD_SUFFIX=osx10.10-xcode6.4
    - os: osx
      osx_image: xcode7.3
      compiler: gcc
      env: AUTOBUILD_SUFFIX=osx10.11-xcode7.3
    - os: osx
      osx_image: xcode8.3
      compiler: gcc
      env: AUTOBUILD_SUFFIX=osx10.12-xcode8.3
    - os: osx
      osx_image: xcode9.3
      compiler: gcc
      env: AUTOBUILD_SUFFIX=osx10.13-xcode9.3

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libsdl2-2.0-0 libegl1-mesa-dev libgles2-mesa-dev libsdl2-dev libjansson-dev libexpat1-dev libcurl4-openssl-dev libpng12-dev libjpeg-dev libspeex-dev libspeexdsp-dev; fi
  - if [[ "$EZ_CONFIG_FILE" == ".config_windows" ]]; then sudo apt-get install -y mingw-w64; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2 sdl2_net sdl2_image sdl2_gfx sdl2_mixer jansson speex speexdsp jq; fi

script:
  - bash ./misc/travis-build/build.sh
